diff --git a/src/Makefile b/src/Makefile
index 4a56d1e8..9ab9f6ec 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -249,6 +249,9 @@ ifneq (,$(findstring LJ_TARGET_ARM64 ,$(TARGET_TESTARCH)))
   endif
   TARGET_LJARCH= arm64
 else
+ifneq (,$(findstring LJ_TARGET_S390X ,$(TARGET_TESTARCH)))
+  TARGET_LJARCH= s390x
+else
 ifneq (,$(findstring LJ_TARGET_PPC ,$(TARGET_TESTARCH)))
   ifneq (,$(findstring LJ_LE 1,$(TARGET_TESTARCH)))
     TARGET_ARCH= -DLJ_ARCH_ENDIAN=LUAJIT_LE
@@ -274,6 +277,7 @@ endif
 endif
 endif
 endif
+endif
 
 ifneq (,$(findstring LJ_TARGET_PS3 1,$(TARGET_TESTARCH)))
   TARGET_SYS= PS3
