diff --git a/src/Makefile b/src/Makefile
index c83abfa0..7eea9385 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -249,6 +249,9 @@ ifneq (,$(findstring LJ_TARGET_ARM64 ,$(TARGET_TESTARCH)))
   endif
   TARGET_LJARCH= arm64
 else
+ifneq (,$(findstring LJ_TARGET_S390X ,$(TARGET_TESTARCH)))
+  TARGET_LJARCH= s390x
+else
 ifneq (,$(findstring LJ_TARGET_PPC ,$(TARGET_TESTARCH)))
   ifneq (,$(findstring LJ_LE 1,$(TARGET_TESTARCH)))
     TARGET_ARCH= -DLJ_ARCH_ENDIAN=LUAJIT_LE
@@ -274,6 +277,7 @@ endif
 endif
 endif
 endif
+endif
 
 ifneq (,$(findstring LJ_TARGET_PS3 1,$(TARGET_TESTARCH)))
   TARGET_SYS= PS3
@@ -357,6 +361,10 @@ else
   ifeq (GNU/kFreeBSD,$(TARGET_SYS))
     TARGET_XLIBS+= -ldl
   endif
+  ifeq (OS/390,$(TARGET_SYS))
+    # On z/OS, (OS/390) we want to just run HLASM, not the integrated assembler
+    ASOPTIONS+= -no-integrated-as -B$(shell pwd)/../../bin
+  endif
 endif
 endif
 endif
